### ISSUE TITLE
damo.php testen?!

### ISSUE THREAD

**Issue by Sebastian99** [BlackCetha/SteamAuthOOP#8]
Hallo,
ich wollte deinen Code mithilfe der demo.php testen. Ich habe dazu aber eine Frage: Was muss ich dann bei der Loginpage eintragen? Wenn ich es leer lasse gehts nicht und wenn ich demo.php eintrage gehts auch nicht!

LG

**Comment by BlackCetha** [comment]
Hallo,
bitte schicke immer mindestens deine Konfigurationsdatei (ohne API-Schlüssel!) mit.
Ebenfalls sind genauere Beschreibungen von dem, was du bereits versucht hast hilfreich.

Davon abgesehen sollte alles auf Englisch laufen, damit später Benutzer mit ähnlichen Problemen die Lösung nachvollziehen können.

Ich würde dich also bitten, einen neuen Issue-Report auf Englisch mit mehr Informationen zu erstellen.

To all non-german readers: This report was closed because it is in german and there is no special information in it.
